item {
  name: "RED"
  id: 1
  display_name: "Red"
}
item {
  name: "YELLOW"
  id: 2
  display_name: "Yellow"
}
item {
  name: "GREEN"
  id: 3
  display_name: "Green"
}
item {
  name: "UNKNOWN"
  id: 4
  display_name: "Unknown"
}